# $$Name$$ - aws environment (Serverless Framework)

    cd backend && npm run build
    cd gen/env/aws && npx serverless deploy --stage $$stage$$

serverless.yml composes the generated srv.yml (functions) and res.yml
(resources); both are regenerated by model-build. Provider settings
(region/stage/runtime) come from the model env entry - change them with
the model, or eject env/aws/serverless.yml.frag for structural edits.
