# $$Name$$ backend - Serverless Framework config (generated; customize via
# tm/env/aws/). Composes the model-generated pieces: per-service function
# definitions (srv.yml) and resources (res.yml) live beside this file and
# are regenerated by model-build - edit the model, not those files.
service: $$name$$-backend

frameworkVersion: '4'

provider:
  name: aws
  runtime: nodejs$$node$$.x
  region: $$region$$
  stage: ${opt:stage, '$$stage$$'}

custom:
  # res.yml derives the IAM role name suffix from this index.
  index:
    BasicLambdaRole: '01'

functions: ${file(./srv.yml)}

resources:
  Resources: ${file(./res.yml)}
